name: Update sitemap lastmod
on:
  push:
    branches: [ main ]
jobs:
  touch-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update date
        run: |
          TODAY=$(date +%F)
          sed -i "s#<lastmod>.*</lastmod>#<lastmod>${TODAY}</lastmod>#g" sitemap.xml
      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "chore: update sitemap lastmod"
            git push
          fi
